services:
  app:
    image: node:lts-alpine3.18
    container_name: ivewatched-app
    working_dir: /app
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ..:/app
    command: sh -c "yarn install && yarn dev"
