services:
  e2e:
    image: ivewatched-e2e
    container_name: ivewatched-e2e
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
      - default
    command: yarn test:e2e
networks:
  default:
    driver: bridge
