services:
  app:
    image: ivewatched-app
    container_name: ivewatched-app
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ..:/app
      - /app/node_modules
    command: pnpm dev
