services:
  e2e:
    image: mcr.microsoft.com/playwright:v1.46.0-jammy
    container_name: ivewatched-e2e
    working_dir: /app
    volumes:
      - ..:/app
    command: sh -c "yarn install && yarn test:e2e"
