name: ivewatched
services:
  db:
    image: postgres
    container_name: ivewatched-app-db
    environment:
      - POSTGRES_URL=postgres://postgres:pass@db:5432/ivewatched
      - POSTGRES_DB=ivewatched
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  db-migration:
    image: ivewatched-app
    container_name: ivewatched-app-db-migration
    environment:
      - POSTGRES_URL=postgres://postgres:pass@db:5432/ivewatched
      - POSTGRES_DB=ivewatched
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    entrypoint: yarn db:migrate
  app:
    image: ivewatched-app
    container_name: ivewatched-app
    environment:
      - POSTGRES_URL=postgres://postgres:pass@db:5432/ivewatched
      - POSTGRES_DB=ivewatched
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - 80:3000
      - 6006:6006
    command: yarn dev
    depends_on:
      - db
      - db-migration
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
      - default
volumes:
  db:
networks:
  default:
    driver: bridge
